wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710441208.589964
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.11.0
      5: 0.16.2
      8:
      - 4
      - 5
      10:
      - 9
      13: darwin-arm64
